FROM ubuntu:latest

RUN apt update
RUN apt upgrade -y

RUN apt install -y vim nmap calibre pandoc libpar-packer-perl perl-doc binutils make wget imagemagick zlib1g zlib1g-dev expat \
    texlive-latex-base texlive-latex-extra texlive-xetex texlive librsvg2-bin \
    texlive-fonts-recommended texlive-fonts-extra texlive-xetex texlive-latex-recommended epubcheck \
    calibre
