variables:
  # Specify the zola version you want to use here
  ZOLA_VERSION: "v0.9.0"

#pages:
deploy:
  image: node:lts
  # This config will only publish changes that are pushed on the master branch
  only:
    - master
  script:
    - apt update && apt install curl -y
    - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
    # Unpack the zola executable
    - tar -xzf zola.tar.gz
    # Execute zola build
    - ./zola build
    # deploy with netlify
    - npm install netlify-cli -g
    - netlify --telemetry-disable
    - netlify deploy --site $NETLIFY_WEBSITE_ID --auth $NETLIFY_TOKEN --prod
  # artifacts:
  #   paths:
  #   - public
