sudo: false


language: go

go:
  - 1.11

git:
  depth: false
  submodules: false


install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
  - cd ${TRAVIS_BUILD_DIR}

script:
  - make

deploy:
  skip_cleanup: true # Important, otherwise the build output would be purged.
  provider: firebase
  token: $FIREBASE_TOKEN
  project: "kerkour-com"
  on:
    branch: master

notifications:
  email:
    on_success: never
