baseURL = "https://kerkour.fr"
languageCode = "en-us"
title = "Sylvain Kerkour"
disableHugoGeneratorInject = true
disableKinds = ["section", "taxonomy", "taxonomyTerm", "tags"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "The canonical web presence of Sylvain Kerkour, creator of Bloom."

[outputs]
  home     = ["HTML"]
