baseURL = "https://www.kerkour.fr/"
languageCode = "en-us"
title = "Sylvain Kerkour"
disableHugoGeneratorInject = true


[markup.goldmark.renderer]
  unsafe= true

[params]
  description = "The canonical web presence of Sylvain Kerkour. I'm on a mission to empower people with open technologies."
  descriptionHtml = "On a mission to empower people with open technologies."
