[Settings]

[build]
  publish = "public/"

####################################################################################################
### kerkour.fr
####################################################################################################

[[redirects]]
  from = "https://focused-bhaskara-c3513b.netlify.com/*"
  to = "https://www.kerkour.fr/:splat"
  status = 301
  force = true


[[redirects]]
  from = "https://kerkour.fr/*"
  to = "https://www.kerkour.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://kerkour.com/*"
  to = "https://www.kerkour.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.kerkour.com/*"
  to = "https://www.kerkour.fr/:splat"
  status = 301
  force = true
