[Settings]

####################################################################################################
### kerkour.fr
####################################################################################################

[[redirects]]
  from = "https://competent-yalow-ad91d6.netlify.com/*"
  to = "https://www.kerkour.fr/:splat"
  status = 301
  force = true


[[redirects]]
  from = "https://kerkour.fr/*"
  to = "https://www.kerkour.fr/:splat"
  status = 301
  force = true
