FROM rust:latest

RUN apt update && apt upgrade -y
RUN apt isntall gcc-mingw-w64-x86-64

RUN rustup target add x86_64-pc-windows-gnu
RUN rustup toolchain install stable-x86_64-pc-windows-gnu


CMD ["cargo", "build", "--target", "x86_64-pc-windows-gnu"]
