docs_dir: src
site_url: https://www.kerkour.fr/the-guide/
repo_url: https://gitlab.com/z0mbie42/kerkour.fr
edit_uri: https://gitlab.com/z0mbie42/kerkour.fr/tree/master/wiki/src/
site_dir: dist/

use_directory_urls: false

theme:
  custom_dir: 'themes/material'
  name: null
  logo: 'assets/icon.png'
  language: en
  feature:
  favicon: '/favicon.svg'
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: 'blue'
    accent: 'blue'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_name: The Guide


nav:
  - Overview: index.md
