title = "Sylvain Kerkour"
description = "The canonical web presence of Sylvain Kerkour."
base_url = "https://kerkour.com.com"
generate_categories_pages = false
generate_tags_pages = false
generate_rss = true
highlight_code = true
highlight_theme = "gruvbox-dark"
compile_sass = true

[extra]
author = "Sylvain Kerkour"
