name: CI

on:
  push:
    branches:
      - main

  schedule:
    # every day at 07:05 UTC
    - cron:  '05 7 * * *'

jobs:
  build:
    # runs-on: ubuntu-latest
    # temporary fix: https://github.com/aws/aws-cli/issues/5262
    runs-on: ubuntu-18.04 


    steps:
      - uses: actions/checkout@v2

      - name: Build and tag Docker image
        run: |
          make docker
          docker tag ghcr.io/skerkour/kerkour.com registry.heroku.com/${{ secrets.HEROKU_APP }}/web

      - name: Login to container registries
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login

      - name: Push Heroku image
        # see here for the details of the release phase https://devcenter.heroku.com/articles/container-registry-and-runtime#release-phase
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP }}/web

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP }} web

      - name: Purge CDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_ID }} --paths "/*"
